package basic;

/**
 * 
 * @author Shri
 * 
 * Every thread in java has some name.
 * It may be default name generated by jvm or customized name provided by programmer.
 * We can get & set name of Thread by using following two methods of Thread class:
 * 		1. public final String getName()
 * 		2. public final void setName(String name)
 *
 */
class MyThread extends Thread{
	public void run(){
		System.out.println("current thread is :" + Thread.currentThread().getName());
	}
}
public class ThreadNameExample {

	public static void main(String[] args) {
		
		System.out.println("current thread is :"+ Thread.currentThread().getName());
		MyThread myThread = new MyThread();
		myThread.setName("MyThread");
		myThread.start();
		
		/**
		 * Default thread name generated by jvm is like : thread-0
		 * output :
		 *			current thread is :main
					current thread is :MyThread		
		 * 
		 */
	}

}
